version: "2"

run:
  go: "1.24"
  tests: true
  timeout: 5m

linters:
  enable:
    - gosec
    - revive
    - govet
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - unconvert
    - goconst
    - staticcheck	
    - errcheck
    - gocritic
    - exhaustive
    - forbidigo
    - bodyclose
    - prealloc
    - makezero

  settings:
    gocyclo:
      min-complexity: 30
    gosec:
      severity: low
    revive: {}                   # put your revive.toml instead

  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters: [errcheck, gosec]
      - path: \.pb\.go$
        linters: [revive, unused]
    paths:
      - third_party/
      - vendor/
      - builtin/
      - examples/
      - '.*\.gen\.go$'

formatters:
  enable:
    - gofmt
    - goimports
    - gci
  exclusions:
    generated: lax
    paths:
      - third_party/
      - vendor/
      - builtin/
      - examples/

issues:
  max-same-issues: 5
