services:
  preservation-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GOOS=linux
        - CGO_ENABLED=1
    container_name: preservation-api
    ports:
      - "6910:6910"
    volumes:
      - preservation_data:/app/data
    command: ["./preservation-api", "serve",
      "--db-connection", "/app/data/preservation_configs.db",
      "--log-level", "debug",
      "--site-domain", "https://cells:8080",
      "--trusted-ips", "127.0.0.1,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16",
      "--allow-insecure-tls"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6910/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - preservation-network

volumes:
  preservation_data:
    driver: local

networks:
  preservation-network:
    external: true