name: build-and-test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read
  pull-requests: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'
        cache: true
        cache-dependency-path: '**/go.sum'

    - name: Run go mod tidy
      run: go mod tidy

    - name: Verify go mod tidy
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "go.mod or go.sum is not up to date"
          git diff
          exit 1
        fi

    - name: Run go vet
      run: go vet ./...

    - name: Build
      env:
        CGO_ENABLED: 1
        PKG_CONFIG_PATH: "/usr/lib/pkgconfig"
      run: go build -v ./...
      timeout-minutes: 5

    - name: Test
      env:
        CGO_ENABLED: 1
        PKG_CONFIG_PATH: "/usr/lib/pkgconfig"
      run: go test -v -race ./...
      timeout-minutes: 5
