name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: read
  packages: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper version information
          
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Build binary
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 1
          GOFLAGS: "-buildvcs=true"  # Ensure VCS info is included in the binary
        run: |
          mkdir -p dist
          # Build with embedded version information
          go build -v \
            -trimpath \
            -o dist/curate-preservation-api \
            .
          
          # Create release archive
          cd dist
          tar czf curate-preservation-api-linux-amd64.tar.gz curate-preservation-api
          sha256sum curate-preservation-api-linux-amd64.tar.gz > curate-preservation-api-linux-amd64.tar.gz.sha256
          cd ..

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/curate-preservation-api-linux-amd64.tar.gz
            dist/curate-preservation-api-linux-amd64.tar.gz.sha256
          generate_release_notes: true

  build-and-push-container:
    runs-on: ubuntu-latest
    needs: build-release

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
